[build]
  base = "ClientApp"
  publish = "build"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  CI = "false"

# Force all routes to index.html for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
