[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables for production
[context.deployment.environment]
  REACT_APP_API_URL = "https://[your-app-name].up.railway.app/api"
  REACT_APP_ENVIRONMENT = "production"

# Environment variables for preview deployments
[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://[your-app-name].up.railway.app/api"
  REACT_APP_ENVIRONMENT = "preview"
